### ISSUE TITLE
[Design] 뼈대구성, prettierrc추가, vue favicon 삭제

### ISSUE THREAD

**Issue by hinyc** [hinyc/wanted-codestates-project-10-11#1]
### ISSUE
- Group: client
- Type: 
- Detail:

### TODO
 - [x] 전체적인 뼈대구성진행 (하드코딩)
 - [x] default formatter 옵션 추가 => frettierrc 
 - [x] vue favicon 삭제
 - [x] ref data 만들기
