### ISSUE TITLE
[Feat] 검색 기능

### ISSUE THREAD

**Issue by hinyc** [hinyc/wanted-codestates-project-10-11#3]
### ISSUE
- Group: client
- Type: 기능추가
- Detail: 검색을 통한 기업선택 기능 `state: selectCompany`

### TODO
 - [x] '데이터'에 존재하는 기업명 입력시 폴리곤, 막대 그래프에 결과값 표시될 수 상태 변경 기능
 - [x] 기업명 삭제시 선택기업 없는 상태로 변경
 - [x] 'enter'로 검색 
 - [x] #17
 - [x] #31
 - [ ]  +@ 키보드이동을 통해 자동완성 기업선택기능
