### ISSUE TITLE
[Feat] 바 그래프

### ISSUE THREAD

**Issue by hinyc** [hinyc/wanted-codestates-project-10-11#6]
### ISSUE
- Group: client
- Type: 
- Detail:

### TODO
 - [x] 결과값을 펜타곤 그래프와 연동하여 표현
 - [x] 숫자데이터는 유저의 점수여야함
 - [x] 각 바의 좌우 총합은 10
 - [x] 막대바의 색상은 개인:`#6e3cf9`, 기업: `#ffd966`
 - [x] 개인점수 중 높은 점수 쪽을 `#0fb459`으로 표시
 - [x] #52
 
📌 ref data 값은 다음값의 기준값
적극성 = 적극적인(Aggressive)
자신감 = 자신있는(Confident)
책임감 = 책임있는(Responsible)
개인셩향 = 개인주의(Indivisual)
수평사고 = 수평적인(Horizontal)
